[workspace]
members = [
  "crates/adapter",
  "crates/application",
  "crates/db",
  "crates/domain",
  "crates/main"
]

[workspace.package]
name = "deligo"
version = "0.1.0"
edition = "2021"
rust-version = "1.72"
authors = ["sebastianrojas"]
